### PR TITLE
feature: create write for kestra page

### LINKED ISSUE #688: Create the write for Kestra page
### Feature description

This is the write for Kestra page, the CTA will be a form from hubspot hyperlink:
Write for the kestra Community

https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=6530-37296&mode=design&t=TIP2aOKLxvRT801D-0

**Slug of the page**: https://kestra.io/write-for-kestra/
**Meta Title**: Write for the Kestra Community
**Meta Description**: If you are a software engineer, or tech enthusiast passionate about orchestration, scheduling, and workflow automation, we at Kestra are inviting you to share your knowledge and insights by writing for us.

Dropdown content of the FAQ:
FAQs

**Compensation**: Original articles are compensated at a competitive rate (exact amount to be specified), payable upon publication.
**Cross-Posting**: You can cross-post your article on other platforms, provided a canonical link to the Kestra site is included.

### PR DESCRIPTION
**Pull request by ridge-kimani**
### Description
- Creates a write about us page. 

Closes #688  

### Type of change
- [x] Feature

### How Has This Been Tested?
- On the browser enter test `/write-for-us` route

### Follow-ups
- [x] There are currently items needed for the PR to be completed:
- ~A background image for the header~
- ~Relevant icons for the "Why Submit a Draft" section.~
- ~The exact color matches for the backgrounds and text.~
- ~Content for the FAQs.~
- ~Links for the submit buttons~.

### Screenshot

Desktop
Web capture_3-1-2024_14332_kestra-8p5rrv6tn-kestra vercel app

### CODE REVIEW

**Comment by ridge-kimani** [comment]
@anna-geller I have updated the URL to `write-for-us` to have similarities with existing URLs like `about-us`, `contact-us`. LMK how that sounds.

**Comment by ridge-kimani** [comment]
I have also added some footnotes for what is left before merging.

**Comment by MartinRst** [comment]
[write for us.zip](https://github.com/kestra-io/docs/files/13702467/write.for.us.zip)

Find attached the images in .svg: 

For the text for each FAQ:

Compensation: Original articles are compensated at a competitive rate, payable upon publication.
Cross-Posting: You can cross-post your article on other platforms, provided a canonical link to the Kestra site is included.

**Comment by MartinRst** [comment]
and here is the link related to the hubspot form: https://share-eu1.hsforms.com/1HWgyBQh8RP6pEZVFW51rOAg7f8j

**Comment by MartinRst** [comment]
Looks good on desktop some issues on mobile though: 

image


image

**Comment by ridge-kimani** [comment]
Web capture_19-12-2023_15210_kestra-3pyvvh639-kestra vercel app

**Comment by MartinRst** [comment]
Here is some last intake and i think we are good afterward: 

the hero image have some weird issues here is a better svg version: 
hero-write-for-kestra

The separator on each section seems to light use: FFFFFF at 10% opacity

Need the color gradient on the numbers and on the arrows.

The arrows also are very weild compared to the design version!


It's just small details otherwise it's an amazing job! Thank you so much Ridge!

**Comment by ridge-kimani** [comment]
Thank you for the feedback @MartinRst! 

The hero icon's svg is identical to the current one. What were the issues you saw? 

Could you also provide the arrow.svg icon too? The current implementation is a placeholder. Also, what are the color gradient values for it and the numbers?

**Comment by MartinRst** [comment]
The image changes are in some shadowing, for the arrows here is the svgs of them
[arows.zip](https://github.com/kestra-io/docs/files/13816966/arows.zip)

After this looks good to ship!

**Comment by ridge-kimani** [comment]
It's ready @MartinRst 🚀

**Comment by MartinRst** [comment]
very nice! thank you Ridge!

**Pull request merged**
