### PR TITLE
Feats docs(loops) : updated loop over a list of values

### PR DESCRIPTION
**Pull request by Adematics**
pull request addresses issue https://github.com/kestra-io/docs/issues/1744 task 2

### CODE REVIEW

**Comment by Ben8t** [comment]
@Adematics can you update your PR by using the ForEach task instead please ?

> Since 0.18 release, a new ForEach core task has been introduced to unify and simplify parallel and sequential task executions, replacing (in a non-breaking way) the EachParallel and EachSequential tasks. Those old tasks are deprecated but you can still use them — take as much time as you need to migrate.

https://kestra.io/plugins/core/tasks/flow/io.kestra.plugin.core.flow.foreach

**Comment by Adematics** [comment]
Alright then, I would check it out. @Ben8t

**Comment by wrussell1999** [comment]
Hey @Adematics, did you make any progress here? Let us know if you need a hand!

**Comment by Adematics** [comment]
Hello @wrussell1999 , I haven't yet updated. sorry for the delay. I will keep you updated when I do. I will get it updated before weekend.

**Comment by Adematics** [comment]
Hello @wrussell1999  @Ben8t 

Kindly look into the `Foreach` Plugin, it seem to have an issue.
I tried using the examples on the official documentation and it kept leading to `invalid entity`

Here is an image of the issue:

foreacherror

**Comment by wrussell1999** [comment]
@Adematics looks like there might be an issue with the plugins on your Kestra instance. I was able to get the same example working on the latest version of the `develop` image. Can you let me know what version of Kestra you're running and if you're using the `no-plugins` image or base one?

**Comment by wrussell1999** [comment]
I did find an [error](https://github.com/kestra-io/kestra/issues/5812) when executing it on `develop`. It works on `latest` though for writing the guide.

**Comment by Adematics** [comment]
Ok I will look into it and send any update

**Comment by Adematics** [comment]
I just checked it out again, and I am still getting the same error.

This is the version I am using with docker

```yaml

kestra:
      image: kestra/kestra:latest-full
      pull_policy: always
      entrypoint: /bin/bash
      # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
      user: "root"
      command:
        - -c
        - /app/kestra server standalone --worker-thread=128
      volumes:
        - kestra-data:/app/storage
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/kestra-wd:/tmp/kestra-wd
      environment:
        KESTRA_CONFIGURATION: |
          datasources:
            postgres:
              url: jdbc:postgresql://postgres:5432/kestra
              driverClassName: org.postgresql.Driver
              username: kestra
              password: k3str4
          kestra:
            server:
              basic-auth:
                enabled: false
                username: admin
                password: kestra
            repository:
              type: postgres
            storage:
              type: minio
              minio:
                endpoint: http://minio
                port: 9000
                accessKey: admin
                secretKey: password
                region: us-east-1
                bucket: warehouse
            queue:
              type: postgres
            tasks:
              tmp-dir:
                path: /tmp/kestra-wd/tmp
            url: http://localhost:8080/
      ports:
        - "8080:8080"
        - "8081:8081"
      depends_on:
        postgres:
          condition: service_started
      networks:
        kestra_net:
        
```

**Review by wrussell1999 — APPROVED** [review]

**Pull request merged**
