### PR TITLE
Feat 1911/enterprise

### PR DESCRIPTION
**Pull request by t-chatoyan**

### CODE REVIEW

**Comment by Nico-Kestra** [comment]
**Plugin box**
Capture d’écran 2024-11-21 à 15 24 53

- Title font-weight 400
- Paragraph font-weight 300
- Plan a rollover effect on the "Get a Demo" button.

**Comment by Nico-Kestra** [comment]
### "Unified" box

Capture d’écran 2024-11-21 à 15 25 57

- All subtitles must be in uppercase.
- The title and subtitle must be aligned with the first block on the left.
- There's a mistake on the button. It should say "**Talk to Sales**"
- Plan a rollover effect on the "Talk to Sales" button.

**Comment by Nico-Kestra** [comment]
**Security, Governance & Scale box**
Capture d’écran 2024-11-21 à 15 30 12

- Don't forget the animation I sent you on Slack.
- The third image is of poor quality.
- Plan a rollover effect on the "Get a Demo" button.
- Title font-weight 400

**Comment by Nico-Kestra** [comment]
Capture d’écran 2024-11-25 à 11 10 32
These blocks should almost be squares.

👇

Capture d’écran 2024-11-25 à 11 12 28

The green glow is cut off; I’ll take a look.

**Comment by Nico-Kestra** [comment]
Capture d’écran 2024-11-25 à 11 10 04
The text must be vertically centered.

**Comment by Nico-Kestra** [comment]
### "Unified" and "Ready to Scale Your Workflows" title

- Title font-weight 400

**Comment by Nico-Kestra** [comment]
Capture d’écran 2024-11-25 à 11 34 50

- Border gradient is missing

**Comment by Nico-Kestra** [comment]
Capture d’écran 2024-11-25 à 11 12 28

- Title font-weight 400

**Comment by Nico-Kestra** [comment]
Capture d’écran 2024-11-25 à 11 39 32

Here, I would stretch the blocks when switching to smaller breakpoints.
Example on the right of the screenshot

**Comment by Nico-Kestra** [comment]
Capture d’écran 2024-11-25 à 12 05 23

There’s a margin here; the visual should be aligned to the edge.

**Comment by Nico-Kestra** [comment]
3 more reviews for mobile:

- Align "Trusted" and L'Oreal logo with top content
- Align Kestra Core card with the top cards.
- Visuals on mobile are of poor quality.

Capture d’écran 2024-11-26 à 12 02 58

IMG_2885

Capture d’écran 2024-11-26 à 12 03 03

**Comment by MartinRst** [comment]
LGTM

**Pull request merged**
